<?php

namespace AppBundle\Repository;

/**
 * FruitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FruitRepository extends \Doctrine\ORM\EntityRepository
{
}
