# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory:
                users:
                    hkool:
                        password: $2y$12$oA8Z.Nqd2j/5NgeLcQCQH.Io4rzWyjTgpbZG./ZHFVcQElAna.322
#                        mondriaan
                        roles: 'ROLE_USER'
                    ijsmaker:
                        password: $2y$12$oA8Z.Nqd2j/5NgeLcQCQH.Io4rzWyjTgpbZG./ZHFVcQElAna.322
                        #                        mondriaan
                        roles: 'ROLE_IJSMAKER'
                    admin:
                        password: $2y$12$8S97NOMi5FDm0S/hFBTmm.T9W4lwSWQ9nI5rTjF0fkg7nV7oTKhzC
                        roles: 'ROLE_ADMIN'
    #                       adminMondriaan
    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
            cost: 12
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
                default_target_path: adminDefault

            logout:
                path:   /logout
                target: /
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }