<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container8s3rmcd\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container8s3rmcd/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container8s3rmcd.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container8s3rmcd\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container8s3rmcd\appDevDebugProjectContainer([
    'container.build_hash' => '8s3rmcd',
    'container.build_id' => 'e718f592',
    'container.build_time' => 1653307383,
], __DIR__.\DIRECTORY_SEPARATOR.'Container8s3rmcd');
